version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tsbooks-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tsuser
      POSTGRES_PASSWORD: tspassword
      POSTGRES_DB: tsbooks
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
